### ISSUE TITLE
When redeploying extension, Commercetools extension config is still present

### ISSUE THREAD

**Issue by matthewdelaney** [commercetools/serverless-commercetools-plugin#13]
Not sure if this is by design but if I deploy a lambda extension then deploy it again, I end up with two extension records on the Commercetools side so the lambda is triggered twice. It would be preferable if any existing extension records for a lambda were deleted upon redeployment. I've tried `serverless remove` as well but that also seems to leave the Commercetools side unaffected.

**Comment by nspeet** [comment]
Hi @matthewdelaney, you can delete extensions with the API by key or id: https://docs.commercetools.com/api/projects/api-extensions

**Comment by nspeet** [comment]
"Please note that you can set a key on extensions and subscriptions. The key prevents the same extension or subscription from being deployed twice from CI/CD and manually deploys."  https://techblog.commercetools.com/serverless-commercetools-integration-6e46596df0ea

**Comment by matthewdelaney** [comment]
The key was what I was looking for, thank you!
